### ISSUE TITLE
smc-python-monitoring: WebSocketBadStatusException

### ISSUE THREAD

**Issue by sonicblind** [gabstopper/smc-python#14]
Hi there,

I am testing the extension smc-python-monitoring and am failing to establish the web socket.
Connection with SMC works, I couldn't find explanation why there is a problem.
Do you perhaps have any idea? Thanks!

```
import os
import smc
from smc import session
from smc.elements.network import Host
from smc.administration.system import System
from smc_monitoring.monitors.logs import LogQuery

session.login(url=f'http://{addr}:{port}', api_key=key, api_version=ver)
print("API VERSION: ", smc.__version__)
print("SYS VERSION: ", System().smc_version)
print('Address:', Host('test_10.10.10.10').address)
query = LogQuery()
for log in query.fetch_live():
    print(log)
session.logout()
```

```
$ ./test.py 
API VERSION:  0.6.1-dev.201802192256
SYS VERSION:  5.10.5 [10037]
Address: 10.10.10.10
Traceback (most recent call last):
  File "./test.py", line 21, in <module>
    for log in query.fetch_live():
  File "/usr/local/lib/python3.6/dist-packages/smc_monitoring/monitors/logs.py", line 199, in fetch_live
    fmt = formatter(clone)
  File "/usr/local/lib/python3.6/dist-packages/smc_monitoring/models/formatters.py", line 142, in __init__
    super(TableFormat, self).__init__(query)
  File "/usr/local/lib/python3.6/dist-packages/smc_monitoring/models/formatters.py", line 84, in __init__
    fields = query.resolve_field_ids(field_ids, **query.sockopt)
  File "/usr/local/lib/python3.6/dist-packages/smc_monitoring/models/query.py", line 227, in resolve_field_ids
    for fields in query.execute():
  File "/usr/local/lib/python3.6/dist-packages/smc_monitoring/models/query.py", line 261, in execute
    with SMCSocketProtocol(self, **self.sockopt) as protocol:
  File "/usr/local/lib/python3.6/dist-packages/smc_monitoring/wsocket.py", line 118, in __enter__
    cookie=session.session_id)
  File "/usr/local/lib/python3.6/dist-packages/websocket/_core.py", line 216, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/local/lib/python3.6/dist-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/lib/python3.6/dist-packages/websocket/_handshake.py", line 135, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d", status)
websocket._exceptions.WebSocketBadStatusException: Handshake status 404
```

**Comment by gabstopper** [comment]
Hi there,
That is interesting, but seems something in the websocket connection is causing this.
Could you add the following to the top of your script and send the output?

```
import logging
logging.getLogger()
logging.basicConfig(
    level=logging.DEBUG, format='%(asctime)s %(levelname)s %(name)s.%(funcName)s: (message)s')
from smc_monitoring.wsocket import websocket
websocket.enableTrace(True)
```

Then rerun.
I just ran a quick test against 5.10.5 and didn't have an issue so we'll have to see if there are additional connection level messages.

**Comment by sonicblind** [comment]
Hi there,

Ok I ran the code you provided and here is the debug output.
To me it looks like SMC answers with 404 as it was unable to find any resource at /5.10/monitoring/log/socket.

```
Connecting proxy...
2018-02-21 10:17:42,843 DEBUG websocket.debug: (message)s
--- request header ---
2018-02-21 10:17:42,843 DEBUG websocket.dump: (message)s
CONNECT mysmc.local:8082 HTTP/1.0


2018-02-21 10:17:42,843 DEBUG websocket.dump: (message)s
-----------------------
2018-02-21 10:17:42,843 DEBUG websocket.dump: (message)s
--- response header ---
2018-02-21 10:17:42,843 DEBUG websocket.trace: (message)s
HTTP/1.1 200 Connection established
2018-02-21 10:17:42,845 DEBUG websocket.trace: (message)s
-----------------------
2018-02-21 10:17:42,845 DEBUG websocket.trace: (message)s
--- request header ---
2018-02-21 10:17:42,845 DEBUG websocket.dump: (message)s
GET /5.10/monitoring/log/socket HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: mysmc.local:8082
Origin: http://mysmc.local:8082
Sec-WebSocket-Key: cbsQ3w3GGdLXLAsi3MEOew==
Sec-WebSocket-Version: 13
Cookie: JSESSIONID=C2DED43BB23507F52693D4524C493A24


2018-02-21 10:17:42,845 DEBUG websocket.dump: (message)s
-----------------------
2018-02-21 10:17:42,845 DEBUG websocket.dump: (message)s
--- response header ---
2018-02-21 10:17:42,845 DEBUG websocket.trace: (message)s
HTTP/1.1 404 Not Found
2018-02-21 10:17:42,848 DEBUG websocket.trace: (message)s
Cache-Control: no-cache
2018-02-21 10:17:42,848 DEBUG websocket.trace: (message)s
Pragma: no-cache
2018-02-21 10:17:42,848 DEBUG websocket.trace: (message)s
Content-Type: text/html; charset=utf-8
2018-02-21 10:17:42,848 DEBUG websocket.trace: (message)s
Proxy-Connection: Keep-Alive
2018-02-21 10:17:42,848 DEBUG websocket.trace: (message)s
Connection: Keep-Alive
2018-02-21 10:17:42,848 DEBUG websocket.trace: (message)s
Content-Length: 660
2018-02-21 10:17:42,848 DEBUG websocket.trace: (message)s
-----------------------
```

**Comment by gabstopper** [comment]
I agree, however it is quite strange. Which platform are you running the SMC on? Is the Log Server on the same machine as the SMC Management Service?
I try with 5.10 and have no problem:

```
--- request header ---
2018-02-21 17:49:11,009 DEBUG websocket.dump: --- request header ---
GET /5.10/monitoring/log/socket HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: 172.18.1.36:8082
Origin: http://172.18.1.36:8082
Sec-WebSocket-Key: 1bJrphR8UJFd8PFGOZ4hoQ==
Sec-WebSocket-Version: 13
Cookie: JSESSIONID=0FF9501F4224CA599616D709A9FA5334


2018-02-21 17:49:11,009 DEBUG websocket.dump: GET /5.10/monitoring/log/socket HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: 172.18.1.36:8082
Origin: http://172.18.1.36:8082
Sec-WebSocket-Key: 1bJrphR8UJFd8PFGOZ4hoQ==
Sec-WebSocket-Version: 13
Cookie: JSESSIONID=0FF9501F4224CA599616D709A9FA5334


-----------------------
2018-02-21 17:49:11,010 DEBUG websocket.dump: -----------------------
--- response header ---
2018-02-21 17:49:11,010 DEBUG websocket.trace: --- response header ---
HTTP/1.1 101 Switching Protocols
2018-02-21 17:49:11,014 DEBUG websocket.trace: HTTP/1.1 101 Switching Protocols
Server: Apache-Coyote/1.1
2018-02-21 17:49:11,014 DEBUG websocket.trace: Server: Apache-Coyote/1.1
Upgrade: websocket
2018-02-21 17:49:11,014 DEBUG websocket.trace: Upgrade: websocket
Connection: upgrade
2018-02-21 17:49:11,015 DEBUG websocket.trace: Connection: upgrade
Sec-WebSocket-Accept: /o0n+DKJsc4Oo0KHEagkrLzskfQ=
2018-02-21 17:49:11,016 DEBUG websocket.trace: Sec-WebSocket-Accept: /o0n+DKJsc4Oo0KHEagkrLzskfQ=
Date: Wed, 21 Feb 2018 23:49:09 GMT
2018-02-21 17:49:11,016 DEBUG websocket.trace: Date: Wed, 21 Feb 2018 23:49:09 GMT
-----------------------
```

**Comment by gabstopper** [comment]
Out of curiousity, does 'mysmc.local' resolve locally? Could you try the IP address of the SMC to rule out DNS?

**Comment by sonicblind** [comment]
Hi there,

DNS is working fine. I replaced my original hostname with mysmc.local only for github forum. 
And also, with the same “session” I am able to fetch smc object, create new policies etc, no connection to API itself is working fine.

Must be something else, directly with the web socket. Maybe nothing is listening on that request URI? 

Thanks.

**Comment by gabstopper** [comment]
Yea, I agree, it seems to indicate that the handshake succeeded but the fetch of the resource did not. 
Can you try making a connection query instead? This uses a different mount point.
The value 'sg_vm' should be the name of a valid engine in SMC.

```
query = ConnectionQuery('sg_vm')
for log in query.fetch_live():
    print(log)
```

**Comment by gabstopper** [comment]
I had another question - in your environment is your Log Server on the same system as the SMC Administration Server you are connecting to?

**Comment by sonicblind** [comment]
Hi there, 

I think I found the error :-)

Looking at the debug output, I was wondering why there was a proxy statement in there.
I know I should not use any proxy, as my SMC is reachable only directly.

```
Connecting proxy...
CONNECT mysmc.local:8082 HTTP/1.0
```


In my previous scripts I disabled the proxy for smc-python with:

`os.environ['NO_PROXY'] = 'mysmc.local'`

But apparently smc-python-monitoring did not accept this statement and still wanted to connect to a proxy.
I searched the code and found the reason in websocket module.

websocket/_url.py is looking for 'no_proxy' key while I used the upper case version of the key.

```
def _is_no_proxy_host(hostname, no_proxy):
    if not no_proxy:
        v = os.environ.get("no_proxy", "").replace(" ", "")
```

When I changed my code to lower case, everything works perfectly!

`os.environ['no_proxy'] = 'mysmc.local'`


Thanks again, I am closing this issue.

**Comment by gabstopper** [comment]
Hi there, thanks for the detailed response! I will add this to the documentation! I think the reason it works fine in smc-python (requests module) is the case insensitive dict that the headers are stored in. Thanks again and i'm glad it's working!
