### ISSUE TITLE
Refresh policy crash when cluste of three firewall

### ISSUE THREAD

**Issue by ad1rie1** [gabstopper/smc-python#60]
Hello, 

When i trie to refresh policy of three firewall, the refresh fail with an error : 
Traceback (most recent call last):
  File "firewall.py", line 266, in <module>
    task_follower = engineSDWAN.refresh(wait_for_finish=True) #This isn't required as engine will still refresh
  File "/usr/local/lib/python3.6/site-packages/smc/core/engine.py", line 1024, in refresh
    timeout=timeout, wait_for_finish=wait_for_finish, **kw)
  File "/usr/local/lib/python3.6/site-packages/smc/administration/tasks.py", line 176, in execute
    resource=resource)
  File "/usr/local/lib/python3.6/site-packages/smc/base/mixins.py", line 25, in make_request
    kwargs.update(href=self.data.get_link(
  File "/usr/local/lib/python3.6/site-packages/smc/base/decorators.py", line 77, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.6/site-packages/smc/base/model.py", line 337, in data
    return LoadElement(self.href)
  File "/usr/local/lib/python3.6/site-packages/smc/base/model.py", line 89, in LoadElement
    result = request.read()
  File "/usr/local/lib/python3.6/site-packages/smc/api/common.py", line 75, in read
    return self._make_request(method='GET')
  File "/usr/local/lib/python3.6/site-packages/smc/api/common.py", line 101, in _make_request
    raise err
smc.api.exceptions.FetchElementFailed: Impossible to retrieve the element 663 of type fw_cluster. Details: Critical JVM error:

there is the simple code : 

engineSDWAN = FirewallCluster(name='PACS-SDWAN')
href = engineSDWAN.href
task_follower = engineSDWAN.refresh(wait_for_finish=True) #This isn't required as engine will still refresh
while not task_follower.done():
           task_follower.wait(3)

Can you help me ? 

Dear

**Comment by gabstopper** [comment]
Which version of SMC are you currently using?

**Comment by ad1rie1** [comment]
hello, SMC version 6.5.5

**Comment by gabstopper** [comment]
Could you set logging on during the call and pass me back the full stack trace? This looks like an SMC related bug based on the initial data.
Add this to top of your script:

```
from smc import session, set_stream_logger
set_stream_logger()
```

**Comment by ad1rie1** [comment]
I have open bug on forcepoint , the trace : 
2019-07-07 20:33:16,604 - smc.api.session - [INFO] - Using SMC API version: 6.5
2019-07-07 20:33:17,362 - smc.api.session - [DEBUG] - Loaded entry points with obtained session.
2019-07-07 20:33:17,861 - smc.api.web - [DEBUG] - Request method: GET
2019-07-07 20:33:17,862 - smc.api.web - [DEBUG] - Request URL: http://192.168.242.10:8082/6.5/elements/api_client/21
2019-07-07 20:33:17,863 - smc.api.web - [DEBUG] - Request headers:
2019-07-07 20:33:17,864 - smc.api.web - [DEBUG] -       'User-Agent': 'python-requests/2.21.0'
2019-07-07 20:33:17,864 - smc.api.web - [DEBUG] -       'Accept-Encoding': 'gzip, deflate'
2019-07-07 20:33:17,865 - smc.api.web - [DEBUG] -       'Accept': '*/*'
2019-07-07 20:33:17,867 - smc.api.web - [DEBUG] -       'Connection': 'keep-alive'
2019-07-07 20:33:17,868 - smc.api.web - [DEBUG] -       'Content-Type': 'application/json'
2019-07-07 20:33:17,869 - smc.api.web - [DEBUG] -       'Cookie': 'JSESSIONID=A8D79E5895ACABE3C9DC33911B7F88A2'
2019-07-07 20:33:17,870 - smc.api.web - [DEBUG] - Request body:
2019-07-07 20:33:17,871 - smc.api.web - [DEBUG] - None
2019-07-07 20:33:17,872 - smc.api.web - [DEBUG] - Response status: 200
2019-07-07 20:33:17,874 - smc.api.web - [DEBUG] - Response headers:
2019-07-07 20:33:17,875 - smc.api.web - [DEBUG] -       'Cache-Control': 'no-transform, max-age=0'
2019-07-07 20:33:17,876 - smc.api.web - [DEBUG] -       'ETag': '"MjE5MTU4MTExNTYxOTc0Mzk0NzI1"'
2019-07-07 20:33:17,877 - smc.api.web - [DEBUG] -       'Content-Type': 'application/json'
2019-07-07 20:33:17,878 - smc.api.web - [DEBUG] -       'Transfer-Encoding': 'chunked'
2019-07-07 20:33:17,879 - smc.api.web - [DEBUG] -       'Date': 'Sun, 07 Jul 2019 18:33:18 GMT'
2019-07-07 20:33:17,880 - smc.api.web - [DEBUG] - Response content:
2019-07-07 20:33:17,882 - smc.api.web - [DEBUG] - {"allowed_to_login_in_shared":true,"console_superuser":false,"enabled":true,"key":21,"link":[{"href":"http://192.168.242.10:8082/6.5/elements/api_client/21","rel":"self","type":"api_client"},{"href":"http://192.168.242.10:8082/6.5/elements/api_client/21/history","rel":"history"},{"href":"http://192.168.242.10:8082/6.5/elements/api_client/21/change_password","rel":"change_password"},{"href":"http://192.168.242.10:8082/6.5/elements/api_client/21/generate_password","rel":"generate_password"},{"href":"http://192.168.242.10:8082/6.5/elements/api_client/21/enable_disable","rel":"enable_disable"}],"name":"BugForcepointAPI","read_only":false,"superuser":true,"system":false}
2019-07-07 20:33:17,884 - smc.api.session - [DEBUG] - Login succeeded for admin: BugForcepointAPI in domain: Shared Domain, session: JSESSIONID=A8D79E5895ACABE3C9DC33911B7F88A2
2019-07-07 20:33:18,138 - smc.api.web - [DEBUG] - Request method: GET
2019-07-07 20:33:18,139 - smc.api.web - [DEBUG] - Request URL: http://192.168.242.10:8082/6.5/elements?filter=PACS-SDWAN&filter_context=fw_cluster&exact_match=True
2019-07-07 20:33:18,140 - smc.api.web - [DEBUG] - Request headers:
2019-07-07 20:33:18,140 - smc.api.web - [DEBUG] -       'User-Agent': 'python-requests/2.21.0'
2019-07-07 20:33:18,141 - smc.api.web - [DEBUG] -       'Accept-Encoding': 'gzip, deflate'
2019-07-07 20:33:18,142 - smc.api.web - [DEBUG] -       'Accept': '*/*'
2019-07-07 20:33:18,143 - smc.api.web - [DEBUG] -       'Connection': 'keep-alive'
2019-07-07 20:33:18,144 - smc.api.web - [DEBUG] -       'Content-Type': 'application/json'
2019-07-07 20:33:18,144 - smc.api.web - [DEBUG] -       'Cookie': 'JSESSIONID=A8D79E5895ACABE3C9DC33911B7F88A2'
2019-07-07 20:33:18,145 - smc.api.web - [DEBUG] - Request body:
2019-07-07 20:33:18,146 - smc.api.web - [DEBUG] - None
2019-07-07 20:33:18,147 - smc.api.web - [DEBUG] - Response status: 200
2019-07-07 20:33:18,148 - smc.api.web - [DEBUG] - Response headers:
2019-07-07 20:33:18,149 - smc.api.web - [DEBUG] -       'ETag': '"YWVkMGFiY2FkYzRkNWU0ZmZlN2I3ZDU4ODViMGEwMzI="'
2019-07-07 20:33:18,149 - smc.api.web - [DEBUG] -       'Content-Type': 'application/json'
2019-07-07 20:33:18,150 - smc.api.web - [DEBUG] -       'Transfer-Encoding': 'chunked'
2019-07-07 20:33:18,151 - smc.api.web - [DEBUG] -       'Date': 'Sun, 07 Jul 2019 18:33:18 GMT'
2019-07-07 20:33:18,152 - smc.api.web - [DEBUG] - Response content:
2019-07-07 20:33:18,153 - smc.api.web - [DEBUG] - {"result":[{"href":"http://192.168.242.10:8082/6.5/elements/fw_cluster/663","name":"PACS-SDWAN","type":"fw_cluster"}]}
2019-07-07 20:33:25,861 - smc.api.web - [DEBUG] - Request method: GET
2019-07-07 20:33:25,862 - smc.api.web - [DEBUG] - Request URL: http://192.168.242.10:8082/6.5/elements/fw_cluster/663
2019-07-07 20:33:25,863 - smc.api.web - [DEBUG] - Request headers:
2019-07-07 20:33:25,863 - smc.api.web - [DEBUG] -       'User-Agent': 'python-requests/2.21.0'
2019-07-07 20:33:25,864 - smc.api.web - [DEBUG] -       'Accept-Encoding': 'gzip, deflate'
2019-07-07 20:33:25,865 - smc.api.web - [DEBUG] -       'Accept': '*/*'
2019-07-07 20:33:25,866 - smc.api.web - [DEBUG] -       'Connection': 'keep-alive'
2019-07-07 20:33:25,868 - smc.api.web - [DEBUG] -       'Content-Type': 'application/json'
2019-07-07 20:33:25,869 - smc.api.web - [DEBUG] -       'Cookie': 'JSESSIONID=A8D79E5895ACABE3C9DC33911B7F88A2'
2019-07-07 20:33:25,870 - smc.api.web - [DEBUG] - Request body:
2019-07-07 20:33:25,870 - smc.api.web - [DEBUG] - None
2019-07-07 20:33:25,871 - smc.api.web - [DEBUG] - Response status: 400
2019-07-07 20:33:25,872 - smc.api.web - [DEBUG] - Response headers:
2019-07-07 20:33:25,873 - smc.api.web - [DEBUG] -       'Content-Type': 'application/json'
2019-07-07 20:33:25,874 - smc.api.web - [DEBUG] -       'Transfer-Encoding': 'chunked'
2019-07-07 20:33:25,874 - smc.api.web - [DEBUG] -       'Date': 'Sun, 07 Jul 2019 18:33:26 GMT'
2019-07-07 20:33:25,875 - smc.api.web - [DEBUG] -       'Connection': 'close'
2019-07-07 20:33:25,876 - smc.api.web - [DEBUG] - Response content:
2019-07-07 20:33:25,877 - smc.api.web - [DEBUG] - {"details":["Details:\nCritical JVM error: "],"message":"Impossible to retrieve the element 663 of type fw_cluster.","status":0}
2019-07-07 20:33:34,284 - smc.api.web - [DEBUG] - Request method: GET
2019-07-07 20:33:34,284 - smc.api.web - [DEBUG] - Request URL: http://192.168.242.10:8082/6.5/elements/fw_cluster/663
2019-07-07 20:33:34,285 - smc.api.web - [DEBUG] - Request headers:
2019-07-07 20:33:34,285 - smc.api.web - [DEBUG] -       'User-Agent': 'python-requests/2.21.0'
2019-07-07 20:33:34,286 - smc.api.web - [DEBUG] -       'Accept-Encoding': 'gzip, deflate'
2019-07-07 20:33:34,287 - smc.api.web - [DEBUG] -       'Accept': '*/*'
2019-07-07 20:33:34,288 - smc.api.web - [DEBUG] -       'Connection': 'keep-alive'
2019-07-07 20:33:34,290 - smc.api.web - [DEBUG] -       'Content-Type': 'application/json'
2019-07-07 20:33:34,290 - smc.api.web - [DEBUG] -       'Cookie': 'JSESSIONID=A8D79E5895ACABE3C9DC33911B7F88A2'
2019-07-07 20:33:34,291 - smc.api.web - [DEBUG] - Request body:
2019-07-07 20:33:34,291 - smc.api.web - [DEBUG] - None
2019-07-07 20:33:34,292 - smc.api.web - [DEBUG] - Response status: 400
2019-07-07 20:33:34,293 - smc.api.web - [DEBUG] - Response headers:
2019-07-07 20:33:34,293 - smc.api.web - [DEBUG] -       'Content-Type': 'application/json'
2019-07-07 20:33:34,294 - smc.api.web - [DEBUG] -       'Transfer-Encoding': 'chunked'
2019-07-07 20:33:34,295 - smc.api.web - [DEBUG] -       'Date': 'Sun, 07 Jul 2019 18:33:35 GMT'
2019-07-07 20:33:34,295 - smc.api.web - [DEBUG] -       'Connection': 'close'
2019-07-07 20:33:34,297 - smc.api.web - [DEBUG] - Response content:
2019-07-07 20:33:34,297 - smc.api.web - [DEBUG] - {"details":["Details:\nCritical JVM error: "],"message":"Impossible to retrieve the element 663 of type fw_cluster.","status":0}

**Comment by gabstopper** [comment]
Thank you for this information. This is clearly an SMC related issue. I'll chase down on this end as well.

**Comment by ad1rie1** [comment]
ok thanck you for the confirmation

**Comment by gabstopper** [comment]
Not a problem. I checked with support and they are escalating to engineering, we hope to have more information soon on the version of release that will address this.
On a related note, as a workaround, could you try to use this method on the engine instead and see if it works? 

```
engine = Engine('master-eng')
if engine.installed_policy:
    poller = engine.upload(engine.installed_policy, wait_for_finish=True)
    while not poller.done():
        poller.wait(5)
        print('Percentage complete {}%'.format(poller.task.progress))
```

The difference is that refresh will simply refresh the assigned policy, whereas upload assigns a policy then deploys it. In the logic above, the upload specifies the already installed policy as the target.

**Comment by ad1rie1** [comment]
Hello, 
Same error here : 
Traceback (most recent call last):
  File "c:\Users\adrien\.vscode\extensions\ms-python.python-2019.6.22090\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\adrien\.vscode\extensions\ms-python.python-2019.6.22090\pythonFiles\lib\python\ptvsd\__main__.py", line 434, in main
    run()
  File "c:\Users\adrien\.vscode\extensions\ms-python.python-2019.6.22090\pythonFiles\lib\python\ptvsd\__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Program Files (x86)\Python37-32\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files (x86)\Python37-32\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files (x86)\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\adrien\Desktop\scriptFail\test.py", line 45, in <module>
    if engine.installed_policy:
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\smc\core\engine.py", line 183, in installed_policy
    for node in self.nodes:
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\smc\core\engine.py", line 459, in nodes
    'nodes'),
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\smc\base\model.py", line 349, in get_relation
    return self.data.get_link(rel)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\smc\base\decorators.py", line 77, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\smc\base\model.py", line 337, in data
    return LoadElement(self.href)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\smc\base\model.py", line 89, in LoadElement
    result = request.read()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\smc\api\common.py", line 75, in read
    return self._make_request(method='GET')
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\smc\api\common.py", line 101, in _make_request
    raise err
smc.api.exceptions.FetchElementFailed: Impossible to retrieve the element 663 of type fw_cluster. Details: Critical JVM error:
